In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("arsenal.csv")
df

,league,season,game,Team,Player,jersey_number,nation,Position,Age,Minutes,...,Match_Week,Match_Day,Kickoff_Time,Home_Team,Away_Team,Match_Score,Venue,Attendance,Referee,Match_Report
0,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Adam Smith,15,ENG,RB,34-108,89,...,1,Fri,20:00,Liverpool,Bournemouth,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...
1,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Adrien Truffert,3,FRA,LB,23-268,90,...,1,Fri,20:00,Liverpool,Bournemouth,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...
2,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Alex Scott,8,ENG,AM,21-359,73,...,1,Fri,20:00,Liverpool,Bournemouth,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...
3,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Antoine Semenyo,24,GHA,RW,25-220,90,...,1,Fri,20:00,Liverpool,Bournemouth,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...
4,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Bafodé Diakité,18,FRA,CB,24-221,90,...,1,Fri,20:00,Liverpool,Bournemouth,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11487,ENG-Premier League,2526,2026-05-24 West Ham United-Leeds United,West Ham United,Mateus Fernandes,18,POR,DM,21-318,90,...,38,Sun,16:00,West Ham United,Leeds United,3–0,London Stadium,62471.0,Anthony Taylor,/en/matches/df8c12d9/West-Ham-United-Leeds-Uni...
11488,ENG-Premier League,2526,2026-05-24 West Ham United-Leeds United,West Ham United,Mohamadou Kanté,55,FRA,MF,20-246,3,...,38,Sun,16:00,West Ham United,Leeds United,3–0,London Stadium,62471.0,Anthony Taylor,/en/matches/df8c12d9/West-Ham-United-Leeds-Uni...
11489,ENG-Premier League,2526,2026-05-24 West Ham United-Leeds United,West Ham United,Pablo,19,BRA,AM,22-142,45,...,38,Sun,16:00,West Ham United,Leeds United,3–0,London Stadium,62471.0,Anthony Taylor,/en/matches/df8c12d9/West-Ham-United-Leeds-Uni...
11490,ENG-Premier League,2526,2026-05-24 West Ham United-Leeds United,West Ham United,Tomáš Souček,28,CZE,DM,31-086,90,...,38,Sun,16:00,West Ham United,Leeds United,3–0,London Stadium,62471.0,Anthony Taylor,/en/matches/df8c12d9/West-Ham-United-Leeds-Uni...
11491,ENG-Premier League,2526,2026-05-24 West Ham United-Leeds United,West Ham United,Valentín Castellanos,11,ARG,FW,27-233,87,...,38,Sun,16:00,West Ham United,Leeds United,3–0,London Stadium,62471.0,Anthony Taylor,/en/matches/df8c12d9/West-Ham-United-Leeds-Uni...

In [3]:
df.isnull().sum()

league                 0
season                 0
game                   0
Team                   0
Player                 0
jersey_number          0
nation                 0
Position               0
Age                    0
Minutes                0
Goals                  0
Assists                0
Penalty_Goals          0
Penalty_Attempts       0
Shots                  0
Shots_On_Target        0
Yellow_Cards           0
Red_Cards              0
Fouls_Committed        0
Fouls_Drawn            0
Offsides               0
Crosses                0
Tackles_Won            0
Interceptions          0
Own_Goals              0
Penalties_Won          0
Penalties_Conceded     0
game_id                0
Match_Date             0
Match_Week             0
Match_Day              0
Kickoff_Time           0
Home_Team              0
Away_Team              0
Match_Score            0
Venue                  0
Attendance            29
Referee                0
Match_Report           0
dtype: int64

In [4]:
df.nunique()

league                   1
season                   1
game                   380
Team                    20
Player                 537
jersey_number           65
nation                  68
Position                17
Age                   4866
Minutes                 90
Goals                    4
Assists                  3
Penalty_Goals            3
Penalty_Attempts         3
Shots                   10
Shots_On_Target          7
Yellow_Cards             3
Red_Cards                2
Fouls_Committed          7
Fouls_Drawn              8
Offsides                 5
Crosses                 19
Tackles_Won              8
Interceptions            7
Own_Goals                3
Penalties_Won            1
Penalties_Conceded       1
game_id                380
Match_Date             114
Match_Week              38
Match_Day                7
Kickoff_Time            17
Home_Team               20
Away_Team               20
Match_Score             31
Venue                   20
Attendance             362
Referee                 23
Match_Report           380
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [7]:
df["Home_Team"].value_counts()

Home_Team
Brighton             592
Fulham               591
Arsenal              590
Newcastle United     588
Tottenham Hotspur    586
Aston Villa          581
Leeds United         581
Burnley              581
Bournemouth          579
Wolves               576
Manchester City      576
Chelsea              572
Manchester Utd       572
Brentford            570
Nottingham Forest    565
Liverpool            563
West Ham United      561
Crystal Palace       559
Everton              559
Sunderland           550
Name: count, dtype: int64

In [8]:
df["Away_Team"].value_counts()

Away_Team
Burnley              597
Bournemouth          590
Fulham               589
Brighton             587
Aston Villa          581
Sunderland           579
Chelsea              576
Liverpool            576
Tottenham Hotspur    574
Nottingham Forest    574
Newcastle United     572
Crystal Palace       572
Leeds United         572
Wolves               571
Arsenal              570
West Ham United      569
Manchester Utd       569
Manchester City      566
Brentford            556
Everton              552
Name: count, dtype: int64

In [9]:
df["Goals"].sum()

np.int64(1005)

In [10]:
df["Goals"].max()

np.int64(3)

In [6]:
df.shape[0] # AMT of games

11492

In [7]:
df.shape[1] # AMT of columns

39

In [4]:
df["Team"].nunique() # How many different opponents

20

In [7]:
df["Team"].nunique() - 1

19

In [12]:
df[(df["Attendance"] > 40000) & (df["Attendance"] < 50000)]

,league,season,game,Team,Player,jersey_number,nation,Position,Age,Minutes,...,Match_Week,Match_Day,Kickoff_Time,Home_Team,Away_Team,Match_Score,Venue,Attendance,Referee,Match_Report
31,ENG-Premier League,2526,2025-08-16 Aston Villa-Newcastle United,Aston Villa,Amadou Onana,24,BEL,DM,24-000,90,...,1,Sat,12:30,Aston Villa,Newcastle United,0–0,Villa Park,42526.0,Craig Pawson,/en/matches/bbdf4739/Aston-Villa-Newcastle-Uni...
32,ENG-Premier League,2526,2025-08-16 Aston Villa-Newcastle United,Aston Villa,Boubacar Kamara,44,FRA,DM,25-266,90,...,1,Sat,12:30,Aston Villa,Newcastle United,0–0,Villa Park,42526.0,Craig Pawson,/en/matches/bbdf4739/Aston-Villa-Newcastle-Uni...
33,ENG-Premier League,2526,2025-08-16 Aston Villa-Newcastle United,Aston Villa,Donyell Malen,17,NED,"FW,MF",26-219,7,...,1,Sat,12:30,Aston Villa,Newcastle United,0–0,Villa Park,42526.0,Craig Pawson,/en/matches/bbdf4739/Aston-Villa-Newcastle-Uni...
34,ENG-Premier League,2526,2025-08-16 Aston Villa-Newcastle United,Aston Villa,Ezri Konsa,4,ENG,CB,27-297,65,...,1,Sat,12:30,Aston Villa,Newcastle United,0–0,Villa Park,42526.0,Craig Pawson,/en/matches/bbdf4739/Aston-Villa-Newcastle-Uni...
35,ENG-Premier League,2526,2025-08-16 Aston Villa-Newcastle United,Aston Villa,John McGinn,7,SCO,AM,30-302,83,...,1,Sat,12:30,Aston Villa,Newcastle United,0–0,Villa Park,42526.0,Craig Pawson,/en/matches/bbdf4739/Aston-Villa-Newcastle-Uni...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10898,ENG-Premier League,2526,2026-05-15 Aston Villa-Liverpool,Liverpool,Milos Kerkez,6,HUN,LB,22-189,90,...,37,Fri,20:00,Aston Villa,Liverpool,4–2,Villa Park,43033.0,Chris Kavanagh,/en/matches/2392e965/Aston-Villa-Liverpool-May...
10899,ENG-Premier League,2526,2026-05-15 Aston Villa-Liverpool,Liverpool,Mohamed Salah,11,EGY,"FW,MF",33-334,17,...,37,Fri,20:00,Aston Villa,Liverpool,4–2,Villa Park,43033.0,Chris Kavanagh,/en/matches/2392e965/Aston-Villa-Liverpool-May...
10900,ENG-Premier League,2526,2026-05-15 Aston Villa-Liverpool,Liverpool,Rio Ngumoha,73,ENG,AM,17-259,90,...,37,Fri,20:00,Aston Villa,Liverpool,4–2,Villa Park,43033.0,Chris Kavanagh,/en/matches/2392e965/Aston-Villa-Liverpool-May...
10901,ENG-Premier League,2526,2026-05-15 Aston Villa-Liverpool,Liverpool,Ryan Gravenberch,38,NED,DM,23-364,65,...,37,Fri,20:00,Aston Villa,Liverpool,4–2,Villa Park,43033.0,Chris Kavanagh,/en/matches/2392e965/Aston-Villa-Liverpool-May...
10902,ENG-Premier League,2526,2026-05-15 Aston Villa-Liverpool,Liverpool,Virgil van Dijk,4,NED,CB,34-311,90,...,37,Fri,20:00,Aston Villa,Liverpool,4–2,Villa Park,43033.0,Chris Kavanagh,/en/matches/2392e965/Aston-Villa-Liverpool-May...

In [18]:
df[df["Match_Day"] == "Sun"].shape[0]

3553

In [17]:
df[df["Position"] == "GK"]

,league,season,game,Team,Player,jersey_number,nation,Position,Age,Minutes,...,Match_Week,Match_Day,Kickoff_Time,Home_Team,Away_Team,Match_Score,Venue,Attendance,Referee,Match_Report
14,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Đorđe Petrović,1,SRB,GK,25-311,90,...,1,Fri,20:00,Liverpool,Bournemouth,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...
16,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Liverpool,Alisson,1,BRA,GK,32-317,90,...,1,Fri,20:00,Liverpool,Bournemouth,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...
37,ENG-Premier League,2526,2025-08-16 Aston Villa-Newcastle United,Aston Villa,Marco Bizot,40,NED,GK,34-159,90,...,1,Sat,12:30,Aston Villa,Newcastle United,0–0,Villa Park,42526.0,Craig Pawson,/en/matches/bbdf4739/Aston-Villa-Newcastle-Uni...
53,ENG-Premier League,2526,2025-08-16 Aston Villa-Newcastle United,Newcastle United,Nick Pope,1,ENG,GK,33-119,90,...,1,Sat,12:30,Aston Villa,Newcastle United,0–0,Villa Park,42526.0,Craig Pawson,/en/matches/bbdf4739/Aston-Villa-Newcastle-Uni...
57,ENG-Premier League,2526,2025-08-16 Brighton-Fulham,Brighton & Hove Albion,Bart Verbruggen,1,NED,GK,22-363,90,...,1,Sat,15:00,Brighton,Fulham,1–1,The American Express Stadium,31478.0,Samuel Barrott,/en/matches/57c49bae/Brighton-and-Hove-Albion-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11428,ENG-Premier League,2526,2026-05-24 Sunderland-Chelsea,Sunderland,Robin Roefs,22,NED,GK,23-127,90,...,38,Sun,16:00,Sunderland,Chelsea,2–1,Stadium of Light,NaN,Chris Kavanagh,/en/matches/384f3785/Sunderland-Chelsea-May-24...
11438,ENG-Premier League,2526,2026-05-24 Tottenham Hotspur-Everton,Everton,Jordan Pickford,1,ENG,GK,32-078,90,...,38,Sun,16:00,Tottenham Hotspur,Everton,1–0,Tottenham Hotspur Stadium,61876.0,Michael Oliver,/en/matches/2dfc43ad/Tottenham-Hotspur-Everton...
11447,ENG-Premier League,2526,2026-05-24 Tottenham Hotspur-Everton,Tottenham Hotspur,Antonín Kinský,31,CZE,GK,23-072,90,...,38,Sun,16:00,Tottenham Hotspur,Everton,1–0,Tottenham Hotspur Stadium,61876.0,Michael Oliver,/en/matches/2dfc43ad/Tottenham-Hotspur-Everton...
11474,ENG-Premier League,2526,2026-05-24 West Ham United-Leeds United,Leeds United,Karl Darlow,26,WAL,GK,35-228,90,...,38,Sun,16:00,West Ham United,Leeds United,3–0,London Stadium,62471.0,Anthony Taylor,/en/matches/df8c12d9/West-Ham-United-Leeds-Uni...
11486,ENG-Premier League,2526,2026-05-24 West Ham United-Leeds United,West Ham United,Mads Hermansen,1,DEN,GK,25-317,90,...,38,Sun,16:00,West Ham United,Leeds United,3–0,London Stadium,62471.0,Anthony Taylor,/en/matches/df8c12d9/West-Ham-United-Leeds-Uni...

In [10]:
df["Match_Score"].dtype

In [11]:
df["Match_Score"] = df["Match_Score"].str.replace("-" , "-", regex = False)

In [12]:
df["home_goals"] = df["Match_Score"].str[0]
df["away_goals"] = df["Match_Score"].str[2]
df

,league,season,game,Team,Player,jersey_number,nation,Position,Age,Minutes,...,Away_Team,Match_Score,Venue,Attendance,Referee,Match_Report,Age_float,Winner,home_goals,away_goals
0,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Adam Smith,15,ENG,RB,34-108,89,...,Bournemouth,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...,34.295890,,4,2
1,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Adrien Truffert,3,FRA,LB,23-268,90,...,Bournemouth,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...,23.734247,,4,2
2,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Alex Scott,8,ENG,AM,21-359,73,...,Bournemouth,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...,21.983562,,4,2
3,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Antoine Semenyo,24,GHA,RW,25-220,90,...,Bournemouth,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...,25.602740,,4,2
4,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Bafodé Diakité,18,FRA,CB,24-221,90,...,Bournemouth,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...,24.605479,,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11487,ENG-Premier League,2526,2026-05-24 West Ham United-Leeds United,West Ham United,Mateus Fernandes,18,POR,DM,21-318,90,...,Leeds United,3–0,London Stadium,62471.0,Anthony Taylor,/en/matches/df8c12d9/West-Ham-United-Leeds-Uni...,21.871233,,3,0
11488,ENG-Premier League,2526,2026-05-24 West Ham United-Leeds United,West Ham United,Mohamadou Kanté,55,FRA,MF,20-246,3,...,Leeds United,3–0,London Stadium,62471.0,Anthony Taylor,/en/matches/df8c12d9/West-Ham-United-Leeds-Uni...,20.673973,,3,0
11489,ENG-Premier League,2526,2026-05-24 West Ham United-Leeds United,West Ham United,Pablo,19,BRA,AM,22-142,45,...,Leeds United,3–0,London Stadium,62471.0,Anthony Taylor,/en/matches/df8c12d9/West-Ham-United-Leeds-Uni...,22.389041,,3,0
11490,ENG-Premier League,2526,2026-05-24 West Ham United-Leeds United,West Ham United,Tomáš Souček,28,CZE,DM,31-086,90,...,Leeds United,3–0,London Stadium,62471.0,Anthony Taylor,/en/matches/df8c12d9/West-Ham-United-Leeds-Uni...,31.235616,,3,0
11491,ENG-Premier League,2526,2026-05-24 West Ham United-Leeds United,West Ham United,Valentín Castellanos,11,ARG,FW,27-233,87,...,Leeds United,3–0,London Stadium,62471.0,Anthony Taylor,/en/matches/df8c12d9/West-Ham-United-Leeds-Uni...,27.638356,,3,0

In [13]:
def find_winner(away_goals, home_goals, Home_Team, Away_Team):
    if home_goals > away_goals:
        return Home_Team
    elif home_goals < away_goals:
        return Away_Team
    else:
        return "Draw"

df["Winner"] = ""
for i in range(len(df)):
    df.loc[i, "Winner"] = find_winner(df.loc[i, "away_goals"] , df.loc[i, "home_goals"] , df.loc[i, "Home_Team"], df.loc[i, "Away_Team"])

In [44]:
df

,league,season,game,Team,Player,jersey_number,nation,Position,Age,Minutes,...,Match_Score,Venue,Attendance,Referee,Match_Report,home_goals,away_goals,Winner,Years_old,Days_old
0,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Adam Smith,15,ENG,RB,34-108,89,...,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...,4,2,Liverpool,34,108
1,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Adrien Truffert,3,FRA,LB,23-268,90,...,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...,4,2,Liverpool,23,268
2,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Alex Scott,8,ENG,AM,21-359,73,...,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...,4,2,Liverpool,21,359
3,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Antoine Semenyo,24,GHA,RW,25-220,90,...,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...,4,2,Liverpool,25,220
4,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Bafodé Diakité,18,FRA,CB,24-221,90,...,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...,4,2,Liverpool,24,221
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11487,ENG-Premier League,2526,2026-05-24 West Ham United-Leeds United,West Ham United,Mateus Fernandes,18,POR,DM,21-318,90,...,3–0,London Stadium,62471.0,Anthony Taylor,/en/matches/df8c12d9/West-Ham-United-Leeds-Uni...,3,0,West Ham United,21,318
11488,ENG-Premier League,2526,2026-05-24 West Ham United-Leeds United,West Ham United,Mohamadou Kanté,55,FRA,MF,20-246,3,...,3–0,London Stadium,62471.0,Anthony Taylor,/en/matches/df8c12d9/West-Ham-United-Leeds-Uni...,3,0,West Ham United,20,246
11489,ENG-Premier League,2526,2026-05-24 West Ham United-Leeds United,West Ham United,Pablo,19,BRA,AM,22-142,45,...,3–0,London Stadium,62471.0,Anthony Taylor,/en/matches/df8c12d9/West-Ham-United-Leeds-Uni...,3,0,West Ham United,22,142
11490,ENG-Premier League,2526,2026-05-24 West Ham United-Leeds United,West Ham United,Tomáš Souček,28,CZE,DM,31-086,90,...,3–0,London Stadium,62471.0,Anthony Taylor,/en/matches/df8c12d9/West-Ham-United-Leeds-Uni...,3,0,West Ham United,31,086
11491,ENG-Premier League,2526,2026-05-24 West Ham United-Leeds United,West Ham United,Valentín Castellanos,11,ARG,FW,27-233,87,...,3–0,London Stadium,62471.0,Anthony Taylor,/en/matches/df8c12d9/West-Ham-United-Leeds-Uni...,3,0,West Ham United,27,233

In [14]:
df["Age_float"] = (
    df["Age"].str.split("-").str[0].astype(float)
    + df["Age"].str.split("-").str[1].astype(float) / 365
)

In [15]:
df

,league,season,game,Team,Player,jersey_number,nation,Position,Age,Minutes,...,Away_Team,Match_Score,Venue,Attendance,Referee,Match_Report,Age_float,Winner,home_goals,away_goals
0,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Adam Smith,15,ENG,RB,34-108,89,...,Bournemouth,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...,34.295890,Liverpool,4,2
1,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Adrien Truffert,3,FRA,LB,23-268,90,...,Bournemouth,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...,23.734247,Liverpool,4,2
2,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Alex Scott,8,ENG,AM,21-359,73,...,Bournemouth,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...,21.983562,Liverpool,4,2
3,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Antoine Semenyo,24,GHA,RW,25-220,90,...,Bournemouth,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...,25.602740,Liverpool,4,2
4,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Bafodé Diakité,18,FRA,CB,24-221,90,...,Bournemouth,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...,24.605479,Liverpool,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11487,ENG-Premier League,2526,2026-05-24 West Ham United-Leeds United,West Ham United,Mateus Fernandes,18,POR,DM,21-318,90,...,Leeds United,3–0,London Stadium,62471.0,Anthony Taylor,/en/matches/df8c12d9/West-Ham-United-Leeds-Uni...,21.871233,West Ham United,3,0
11488,ENG-Premier League,2526,2026-05-24 West Ham United-Leeds United,West Ham United,Mohamadou Kanté,55,FRA,MF,20-246,3,...,Leeds United,3–0,London Stadium,62471.0,Anthony Taylor,/en/matches/df8c12d9/West-Ham-United-Leeds-Uni...,20.673973,West Ham United,3,0
11489,ENG-Premier League,2526,2026-05-24 West Ham United-Leeds United,West Ham United,Pablo,19,BRA,AM,22-142,45,...,Leeds United,3–0,London Stadium,62471.0,Anthony Taylor,/en/matches/df8c12d9/West-Ham-United-Leeds-Uni...,22.389041,West Ham United,3,0
11490,ENG-Premier League,2526,2026-05-24 West Ham United-Leeds United,West Ham United,Tomáš Souček,28,CZE,DM,31-086,90,...,Leeds United,3–0,London Stadium,62471.0,Anthony Taylor,/en/matches/df8c12d9/West-Ham-United-Leeds-Uni...,31.235616,West Ham United,3,0
11491,ENG-Premier League,2526,2026-05-24 West Ham United-Leeds United,West Ham United,Valentín Castellanos,11,ARG,FW,27-233,87,...,Leeds United,3–0,London Stadium,62471.0,Anthony Taylor,/en/matches/df8c12d9/West-Ham-United-Leeds-Uni...,27.638356,West Ham United,3,0

In [3]:
df["Goals"].sum()

np.int64(1005)

In [23]:
wins = (df["Winner"] == "Arsenal").sum()
wins

np.int64(804)

In [30]:
games = df["game"].nunique()
wins = (df["Winner"] == "Arsenal").sum()
losses = games/10 - wins
losses

np.int64(-424)

In [32]:
draw = (df["Winner"] == "Draw").sum()
draw

np.int64(3064)

In [36]:
df["home_goals"]=df["home_goals"].astype(int)
df["away_goals"]=df["away_goals"].astype(int)
df.dtypes

league                    str
season                  int64
game                      str
Team                      str
Player                    str
jersey_number           int64
nation                    str
Position                  str
Age                       str
Minutes                 int64
Goals                   int64
Assists                 int64
Penalty_Goals           int64
Penalty_Attempts        int64
Shots                   int64
Shots_On_Target         int64
Yellow_Cards            int64
Red_Cards               int64
Fouls_Committed         int64
Fouls_Drawn             int64
Offsides                int64
Crosses                 int64
Tackles_Won             int64
Interceptions           int64
Own_Goals               int64
Penalties_Won           int64
Penalties_Conceded      int64
game_id                   str
Match_Date                str
Match_Week              int64
Match_Day                 str
Kickoff_Time              str
Home_Team                 str
Away_Team                 str
Match_Score               str
Venue                     str
Attendance            float64
Referee                   str
Match_Report              str
Age_float             float64
Winner                    str
home_goals              int64
away_goals              int64
dtype: object

In [39]:
df[((df["home_goals"]>3) | (df["away_goals"]>3))]

,league,season,game,Team,Player,jersey_number,nation,Position,Age,Minutes,...,Away_Team,Match_Score,Venue,Attendance,Referee,Match_Report,Age_float,Winner,home_goals,away_goals
0,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Adam Smith,15,ENG,RB,34-108,89,...,Bournemouth,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...,34.295890,Liverpool,4,2
1,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Adrien Truffert,3,FRA,LB,23-268,90,...,Bournemouth,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...,23.734247,Liverpool,4,2
2,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Alex Scott,8,ENG,AM,21-359,73,...,Bournemouth,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...,21.983562,Liverpool,4,2
3,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Antoine Semenyo,24,GHA,RW,25-220,90,...,Bournemouth,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...,25.602740,Liverpool,4,2
4,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Bafodé Diakité,18,FRA,CB,24-221,90,...,Bournemouth,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...,24.605479,Liverpool,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10898,ENG-Premier League,2526,2026-05-15 Aston Villa-Liverpool,Liverpool,Milos Kerkez,6,HUN,LB,22-189,90,...,Liverpool,4–2,Villa Park,43033.0,Chris Kavanagh,/en/matches/2392e965/Aston-Villa-Liverpool-May...,22.517808,Aston Villa,4,2
10899,ENG-Premier League,2526,2026-05-15 Aston Villa-Liverpool,Liverpool,Mohamed Salah,11,EGY,"FW,MF",33-334,17,...,Liverpool,4–2,Villa Park,43033.0,Chris Kavanagh,/en/matches/2392e965/Aston-Villa-Liverpool-May...,33.915068,Aston Villa,4,2
10900,ENG-Premier League,2526,2026-05-15 Aston Villa-Liverpool,Liverpool,Rio Ngumoha,73,ENG,AM,17-259,90,...,Liverpool,4–2,Villa Park,43033.0,Chris Kavanagh,/en/matches/2392e965/Aston-Villa-Liverpool-May...,17.709589,Aston Villa,4,2
10901,ENG-Premier League,2526,2026-05-15 Aston Villa-Liverpool,Liverpool,Ryan Gravenberch,38,NED,DM,23-364,65,...,Liverpool,4–2,Villa Park,43033.0,Chris Kavanagh,/en/matches/2392e965/Aston-Villa-Liverpool-May...,23.997260,Aston Villa,4,2
10902,ENG-Premier League,2526,2026-05-15 Aston Villa-Liverpool,Liverpool,Virgil van Dijk,4,NED,CB,34-311,90,...,Liverpool,4–2,Villa Park,43033.0,Chris Kavanagh,/en/matches/2392e965/Aston-Villa-Liverpool-May...,34.852055,Aston Villa,4,2

In [46]:
df[df["Age_float"]<= 20.0][["Team", "Player", "Age", "jersey_number" ]]

                    Team              Player     Age  jersey_number
7            Bournemouth   Eli Junior Kroupi  19-053             22
52      Newcastle United         Lewis Miley  19-107             67
81                Fulham         Joshua King  18-225             24
90            Sunderland          Chris Rigg  18-059             11
134    Tottenham Hotspur         Archie Gray  19-157             14
...                  ...                 ...     ...            ...
11336          Liverpool          Trey Nyoni  18-328             42
11375        Bournemouth   Eli Junior Kroupi  19-335             22
11383        Bournemouth               Rayan  19-294             37
11418         Sunderland          Chris Rigg  18-340             11
11433            Everton  Harrison Armstrong  19-125             45

[502 rows x 4 columns]

In [48]:
df[df["Winner"] == "Liverpool"][["game" , "Venue", "Match_Score"]]

                                      game    Venue Match_Score
0         2025-08-15 Liverpool-Bournemouth  Anfield         4–2
1         2025-08-15 Liverpool-Bournemouth  Anfield         4–2
2         2025-08-15 Liverpool-Bournemouth  Anfield         4–2
3         2025-08-15 Liverpool-Bournemouth  Anfield         4–2
4         2025-08-15 Liverpool-Bournemouth  Anfield         4–2
...                                    ...      ...         ...
10154  2026-04-25 Liverpool-Crystal Palace  Anfield         3–1
10155  2026-04-25 Liverpool-Crystal Palace  Anfield         3–1
10156  2026-04-25 Liverpool-Crystal Palace  Anfield         3–1
10157  2026-04-25 Liverpool-Crystal Palace  Anfield         3–1
10158  2026-04-25 Liverpool-Crystal Palace  Anfield         3–1

[508 rows x 3 columns]

In [49]:
df[df["Attendance"]>= 50000]

,league,season,game,Team,Player,jersey_number,nation,Position,Age,Minutes,...,Away_Team,Match_Score,Venue,Attendance,Referee,Match_Report,Age_float,Winner,home_goals,away_goals
0,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Adam Smith,15,ENG,RB,34-108,89,...,Bournemouth,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...,34.295890,Liverpool,4,2
1,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Adrien Truffert,3,FRA,LB,23-268,90,...,Bournemouth,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...,23.734247,Liverpool,4,2
2,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Alex Scott,8,ENG,AM,21-359,73,...,Bournemouth,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...,21.983562,Liverpool,4,2
3,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Antoine Semenyo,24,GHA,RW,25-220,90,...,Bournemouth,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...,25.602740,Liverpool,4,2
4,ENG-Premier League,2526,2025-08-15 Liverpool-Bournemouth,Bournemouth,Bafodé Diakité,18,FRA,CB,24-221,90,...,Bournemouth,4–2,Anfield,60315.0,Anthony Taylor,/en/matches/a071faa8/Liverpool-Bournemouth-Aug...,24.605479,Liverpool,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11487,ENG-Premier League,2526,2026-05-24 West Ham United-Leeds United,West Ham United,Mateus Fernandes,18,POR,DM,21-318,90,...,Leeds United,3–0,London Stadium,62471.0,Anthony Taylor,/en/matches/df8c12d9/West-Ham-United-Leeds-Uni...,21.871233,West Ham United,3,0
11488,ENG-Premier League,2526,2026-05-24 West Ham United-Leeds United,West Ham United,Mohamadou Kanté,55,FRA,MF,20-246,3,...,Leeds United,3–0,London Stadium,62471.0,Anthony Taylor,/en/matches/df8c12d9/West-Ham-United-Leeds-Uni...,20.673973,West Ham United,3,0
11489,ENG-Premier League,2526,2026-05-24 West Ham United-Leeds United,West Ham United,Pablo,19,BRA,AM,22-142,45,...,Leeds United,3–0,London Stadium,62471.0,Anthony Taylor,/en/matches/df8c12d9/West-Ham-United-Leeds-Uni...,22.389041,West Ham United,3,0
11490,ENG-Premier League,2526,2026-05-24 West Ham United-Leeds United,West Ham United,Tomáš Souček,28,CZE,DM,31-086,90,...,Leeds United,3–0,London Stadium,62471.0,Anthony Taylor,/en/matches/df8c12d9/West-Ham-United-Leeds-Uni...,31.235616,West Ham United,3,0
11491,ENG-Premier League,2526,2026-05-24 West Ham United-Leeds United,West Ham United,Valentín Castellanos,11,ARG,FW,27-233,87,...,Leeds United,3–0,London Stadium,62471.0,Anthony Taylor,/en/matches/df8c12d9/West-Ham-United-Leeds-Uni...,27.638356,West Ham United,3,0

In [61]:
df[df["Player"] == "Mohammed Salah"]["Goals"].sum()

np.int64(0)