In [44]:
import numpy as np
import pandas as pd

In [45]:
# 0d array --> d = dimesional and array = list
a = np.array(37227)
print(a)

37227

In [46]:
# 1d array --> d = dimesional and array = list
a1 = np.array([1, 2, 3, 4, 5])
print(a1)

[1 2 3 4 5]

In [47]:
# 2d array --> d = dimesional and array = list

a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [48]:
# 3d array --> d = dimesional and array = list
a3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]

In [49]:
ar1 = np.array([1, 2, 3, 4, 5])

print("element index: ", ar1[0])
print("element index: ", ar1[0:3])
print("element index: ", ar1[2:])
print("element index: ", ar1[::-1])

element index:  1
element index:  [1 2 3]
element index:  [3 4 5]
element index:  [5 4 3 2 1]

In [50]:
ar2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar2)
print(ar2[0,0])
print(ar2[1,2])
print(ar2[1])
print(ar2[:,1])

print(ar2[0:2,1:3])
print(ar2[1:3,1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
6
[4 5 6]
[2 5 8]
[[2 3]
 [5 6]]
[[5 6]
 [8 9]]

In [51]:
ae2 = np.array([[1,2,3],[4,5,6]])
af2 = np.array([[7,8,9],[10,11,12]])
print(ae2+af2)
print(ae2-af2)
print(ae2/af2)
print(ae2*af2)

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
[[ 7 16 27]
 [40 55 72]]

In [52]:
print(np.dot(ae2,af2.T))

[[ 50  68]
 [122 167]]

In [53]:
print(ae2.T)

[[1 4]
 [2 5]
 [3 6]]

In [54]:
# Creating a sample DataFrame with sales data
data = {'Product': ['A', 'B', 'A', 'C', 'B', 'C'],
'Quantity': [10, 15, 8, 12, 7, 9],
'Price': [20.0, 25.0, 18.0, 30.0, 22.0, 28.0]}

In [55]:
df = pd.DataFrame(data)
df

  Product  Quantity  Price
0       A        10   20.0
1       B        15   25.0
2       A         8   18.0
3       C        12   30.0
4       B         7   22.0
5       C         9   28.0

In [56]:
df['Revenue'] = np.multiply(df["Quantity"], df['Price'])

In [57]:
df

  Product  Quantity  Price  Revenue
0       A        10   20.0    200.0
1       B        15   25.0    375.0
2       A         8   18.0    144.0
3       C        12   30.0    360.0
4       B         7   22.0    154.0
5       C         9   28.0    252.0

In [58]:
df1 = pd.DataFrame({"temp":[2,6,8,10] , "windspeed" : [45,78,32,5]})
df1

   temp  windspeed
0     2         45
1     6         78
2     8         32
3    10          5

In [60]:
df2 = pd.DataFrame({"temp":[1,3,5,7] , "windspeed" : [67,56,93,76]})
df2

   temp  windspeed
0     1         67
1     3         56
2     5         93
3     7         76

In [62]:
newdf = pd.concat([df1,df2])
newdf

   temp  windspeed
0     2         45
1     6         78
2     8         32
3    10          5
0     1         67
1     3         56
2     5         93
3     7         76

In [168]:
res = pd.concat([df1,df2], ignore_index = True)
res

   temp  windspeed
0     2         45
1     6         78
2     8         32
3    10          5
4     1         67
5     3         56
6     5         93
7     7         76

In [169]:
columnconcat = pd.concat([df1,df2], axis = 1)

In [170]:
columnconcat

   temp  windspeed  temp  windspeed
0     2         45     1         67
1     6         78     3         56
2     8         32     5         93
3    10          5     7         76

In [234]:
df3 = pd.DataFrame({"humidity":[49,83,34,67] , "precipitation" : [96,25,85,68]})
df3

   humidity  precipitation
0        49             96
1        83             25
2        34             85
3        67             68

In [237]:
columnconcat1 = pd.concat([df1,df3], axis = 1)

In [238]:
columnconcat1

   temp  windspeed  humidity  precipitation
0     2         45        49             96
1     6         78        83             25
2     8         32        34             85
3    10          5        67             68

In [240]:
rowconcat = pd.concat([df1,df3])
rowconcat

   temp  windspeed  humidity  precipitation
0   2.0       45.0       NaN            NaN
1   6.0       78.0       NaN            NaN
2   8.0       32.0       NaN            NaN
3  10.0        5.0       NaN            NaN
0   NaN        NaN      49.0           96.0
1   NaN        NaN      83.0           25.0
2   NaN        NaN      34.0           85.0
3   NaN        NaN      67.0           68.0

In [244]:
data_personal = {
    'Employee_ID': [101, 102, 103, 104],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Gender': ['Female', 'Male', 'Male', 'Male']
}
df_personal = pd.DataFrame(data_personal)

# Sample DataFrame 2: Employee salary information
data_salary = {
    'Employee_ID': [101, 102, 103, 104],
    'Salary': [60000, 70000, 65000, 75000]
}
df_salary = pd.DataFrame(data_salary)

# Sample DataFrame 3: Employee department information
data_department = {
    'Employee_ID': [101, 103, 104, 105],
    'Department': ['HR', 'Finance', 'IT', 'Marketing']
}
df_department = pd.DataFrame(data_department)

In [247]:
df_personal

   Employee_ID     Name  Gender
0          101    Alice  Female
1          102      Bob    Male
2          103  Charlie    Male
3          104    David    Male

In [248]:
df_salary

   Employee_ID  Salary
0          101   60000
1          102   70000
2          103   65000
3          104   75000

In [250]:
merge1 = pd.concat([df_salary, df_personal, df_department])
merge1

   Employee_ID   Salary     Name  Gender Department
0          101  60000.0      NaN     NaN        NaN
1          102  70000.0      NaN     NaN        NaN
2          103  65000.0      NaN     NaN        NaN
3          104  75000.0      NaN     NaN        NaN
0          101      NaN    Alice  Female        NaN
1          102      NaN      Bob    Male        NaN
2          103      NaN  Charlie    Male        NaN
3          104      NaN    David    Male        NaN
0          101      NaN      NaN     NaN         HR
1          103      NaN      NaN     NaN    Finance
2          104      NaN      NaN     NaN         IT
3          105      NaN      NaN     NaN  Marketing

In [251]:
df_department

   Employee_ID Department
0          101         HR
1          103    Finance
2          104         IT
3          105  Marketing

In [254]:
finalmente = pd.concat([df_personal, df_department,df_salary], axis = 1)

In [255]:
finalmente

   Employee_ID     Name  Gender  Employee_ID Department  Employee_ID  Salary
0          101    Alice  Female          101         HR          101   60000
1          102      Bob    Male          103    Finance          102   70000
2          103  Charlie    Male          104         IT          103   65000
3          104    David    Male          105  Marketing          104   75000

In [259]:
innerconcat = pd.concat([df_personal, df_department, df_salary], join = "inner")
innerconcat

   Employee_ID
0          101
1          102
2          103
3          104
0          101
1          103
2          104
3          105
0          101
1          102
2          103
3          104

In [262]:
innerconcat1 = pd.concat([df_personal ,df_salary], join = "inner", axis = 1)
innerconcat1

   Employee_ID     Name  Gender  Employee_ID  Salary
0          101    Alice  Female          101   60000
1          102      Bob    Male          102   70000
2          103  Charlie    Male          103   65000
3          104    David    Male          104   75000

SyntaxError: invalid character '👍' (U+1F44D) (1167948050.py, line 1)