In [10]:
import pandas as pd #run this before anything!!!!!

In [9]:
data = {
    "Name": [
        "Roger Federer",
        "Novak Djokovic",
        "Carlos Alcaraz",
        "Aryna Sabalenka",
        "Rafael Nadal",
        "Iga Swiatek",
        "Jannik Sinner",
        "Coco Gauff"
    ],

    "Age": [
        45, 39, 23, 28,
        40, 25, 25, 22
    ],

    "Gender": ["M", "M", "M", "F", "M", "M", "M", "F"],

    "Retired?": [
        "Yes", "No", "No", "No",
        "Yes", "No", "No", "No"
    ],

    "Net Worth (M)": [
        420, 180, 85, 27.4,
        220, 30, 20, 15
    ],

    "Grand Slam Titles": [
        20, 24, 2, 4,
        22, 6, 4, 1
    ],

    "Country": [
        "Switzerland",
        "Serbia",
        "Spain",
        "Belarus",
        "Spain",
        "Poland",
        "Italy",
        "USA"
    ],

    "Playing Style": [
        "All-round",
        "All-round",
        "Aggressive",
        "Aggressive",
        "Left-handed",
        "Baseline",
        "Baseline",
        "Aggressive"
    ]
}

df = pd.DataFrame(data, index = [1, 2, 3, 4, 5, 6, 7, 8])
df

,Name,Age,Gender,Retired?,Net Worth (M),Grand Slam Titles,Country,Playing Style
1,Roger Federer,45,M,Yes,420.0,20,Switzerland,All-round
2,Novak Djokovic,39,M,No,180.0,24,Serbia,All-round
3,Carlos Alcaraz,23,M,No,85.0,2,Spain,Aggressive
4,Aryna Sabalenka,28,F,No,27.4,4,Belarus,Aggressive
5,Rafael Nadal,40,M,Yes,220.0,22,Spain,Left-handed
6,Iga Swiatek,25,M,No,30.0,6,Poland,Baseline
7,Jannik Sinner,25,M,No,20.0,4,Italy,Baseline
8,Coco Gauff,22,F,No,15.0,1,USA,Aggressive

In [13]:
#first 5 rows
df.head()

,Name,Age,Gender,Retired?,Net Worth (M),Grand Slam Titles,Country,Playing Style
1,Roger Federer,45,M,Yes,420.0,20,Switzerland,All-round
2,Novak Djokovic,39,M,No,180.0,24,Serbia,All-round
3,Carlos Alcaraz,23,M,No,85.0,2,Spain,Aggressive
4,Aryna Sabalenka,28,F,No,27.4,4,Belarus,Aggressive
5,Rafael Nadal,40,M,Yes,220.0,22,Spain,Left-handed

In [15]:
df.tail()
#last 5

,Name,Age,Gender,Retired?,Net Worth (M),Grand Slam Titles,Country,Playing Style
4,Aryna Sabalenka,28,F,No,27.4,4,Belarus,Aggressive
5,Rafael Nadal,40,M,Yes,220.0,22,Spain,Left-handed
6,Iga Swiatek,25,M,No,30.0,6,Poland,Baseline
7,Jannik Sinner,25,M,No,20.0,4,Italy,Baseline
8,Coco Gauff,22,F,No,15.0,1,USA,Aggressive

In [16]:
df["Name"]

1      Roger Federer
2     Novak Djokovic
3     Carlos Alcaraz
4    Aryna Sabalenka
5       Rafael Nadal
6        Iga Swiatek
7      Jannik Sinner
8         Coco Gauff
Name: Name, dtype: str

In [18]:
df[["Name", "Country"]]

              Name      Country
1    Roger Federer  Switzerland
2   Novak Djokovic       Serbia
3   Carlos Alcaraz        Spain
4  Aryna Sabalenka      Belarus
5     Rafael Nadal        Spain
6      Iga Swiatek       Poland
7    Jannik Sinner        Italy
8       Coco Gauff          USA

In [19]:
df.shape

(8, 8)

In [20]:
df.columns

Index(['Name', 'Age', 'Gender', 'Retired?', 'Net Worth (M)',
       'Grand Slam Titles', 'Country', 'Playing Style'],
      dtype='str')

In [21]:
df.dtypes

Name                     str
Age                    int64
Gender                   str
Retired?                 str
Net Worth (M)        float64
Grand Slam Titles      int64
Country                  str
Playing Style            str
dtype: object

In [23]:
df.iloc[0]

Name                 Roger Federer
Age                             45
Gender                           M
Retired?                       Yes
Net Worth (M)                420.0
Grand Slam Titles               20
Country                Switzerland
Playing Style            All-round
Name: 1, dtype: object

In [24]:
df.iloc[-1]

Name                 Coco Gauff
Age                          22
Gender                        F
Retired?                     No
Net Worth (M)              15.0
Grand Slam Titles             1
Country                     USA
Playing Style        Aggressive
Name: 8, dtype: object

In [25]:
df.iloc[0:3]

,Name,Age,Gender,Retired?,Net Worth (M),Grand Slam Titles,Country,Playing Style
1,Roger Federer,45,M,Yes,420.0,20,Switzerland,All-round
2,Novak Djokovic,39,M,No,180.0,24,Serbia,All-round
3,Carlos Alcaraz,23,M,No,85.0,2,Spain,Aggressive

In [26]:
df.iloc[4:6]

,Name,Age,Gender,Retired?,Net Worth (M),Grand Slam Titles,Country,Playing Style
5,Rafael Nadal,40,M,Yes,220.0,22,Spain,Left-handed
6,Iga Swiatek,25,M,No,30.0,6,Poland,Baseline

In [27]:
df.iloc[0:4, 0:2]

              Name  Age
1    Roger Federer   45
2   Novak Djokovic   39
3   Carlos Alcaraz   23
4  Aryna Sabalenka   28

In [28]:
df.iloc[3, [0, 6]]

Name       Aryna Sabalenka
Country            Belarus
Name: 4, dtype: str

In [30]:
df.loc[5, "Grand Slam Titles"]

np.int64(22)

In [31]:
df.loc[4, ["Name", "Net Worth (M)"]]

Name             Aryna Sabalenka
Net Worth (M)               27.4
Name: 4, dtype: object

In [33]:
df[df["Age"] < 30]

,Name,Age,Gender,Retired?,Net Worth (M),Grand Slam Titles,Country,Playing Style
3,Carlos Alcaraz,23,M,No,85.0,2,Spain,Aggressive
4,Aryna Sabalenka,28,F,No,27.4,4,Belarus,Aggressive
6,Iga Swiatek,25,M,No,30.0,6,Poland,Baseline
7,Jannik Sinner,25,M,No,20.0,4,Italy,Baseline
8,Coco Gauff,22,F,No,15.0,1,USA,Aggressive

In [34]:
df[df["Country"] == "Spain"]

,Name,Age,Gender,Retired?,Net Worth (M),Grand Slam Titles,Country,Playing Style
3,Carlos Alcaraz,23,M,No,85.0,2,Spain,Aggressive
5,Rafael Nadal,40,M,Yes,220.0,22,Spain,Left-handed

In [35]:
df[df["Playing Style"] == "Baseline"]

,Name,Age,Gender,Retired?,Net Worth (M),Grand Slam Titles,Country,Playing Style
6,Iga Swiatek,25,M,No,30.0,6,Poland,Baseline
7,Jannik Sinner,25,M,No,20.0,4,Italy,Baseline

In [36]:
df[df["Net Worth (M)"] >= 100.0]

,Name,Age,Gender,Retired?,Net Worth (M),Grand Slam Titles,Country,Playing Style
1,Roger Federer,45,M,Yes,420.0,20,Switzerland,All-round
2,Novak Djokovic,39,M,No,180.0,24,Serbia,All-round
5,Rafael Nadal,40,M,Yes,220.0,22,Spain,Left-handed

In [37]:
df[(df["Retired?"]== "Yes") & (df["Country"]== "Switzerland")]

,Name,Age,Gender,Retired?,Net Worth (M),Grand Slam Titles,Country,Playing Style
1,Roger Federer,45,M,Yes,420.0,20,Switzerland,All-round

In [38]:
df.sort_values("Age")

,Name,Age,Gender,Retired?,Net Worth (M),Grand Slam Titles,Country,Playing Style
8,Coco Gauff,22,F,No,15.0,1,USA,Aggressive
3,Carlos Alcaraz,23,M,No,85.0,2,Spain,Aggressive
6,Iga Swiatek,25,M,No,30.0,6,Poland,Baseline
7,Jannik Sinner,25,M,No,20.0,4,Italy,Baseline
4,Aryna Sabalenka,28,F,No,27.4,4,Belarus,Aggressive
2,Novak Djokovic,39,M,No,180.0,24,Serbia,All-round
5,Rafael Nadal,40,M,Yes,220.0,22,Spain,Left-handed
1,Roger Federer,45,M,Yes,420.0,20,Switzerland,All-round

In [39]:
df.sort_values("Net Worth (M)", ascending = False)

,Name,Age,Gender,Retired?,Net Worth (M),Grand Slam Titles,Country,Playing Style
1,Roger Federer,45,M,Yes,420.0,20,Switzerland,All-round
5,Rafael Nadal,40,M,Yes,220.0,22,Spain,Left-handed
2,Novak Djokovic,39,M,No,180.0,24,Serbia,All-round
3,Carlos Alcaraz,23,M,No,85.0,2,Spain,Aggressive
6,Iga Swiatek,25,M,No,30.0,6,Poland,Baseline
4,Aryna Sabalenka,28,F,No,27.4,4,Belarus,Aggressive
7,Jannik Sinner,25,M,No,20.0,4,Italy,Baseline
8,Coco Gauff,22,F,No,15.0,1,USA,Aggressive

In [41]:
df.sort_values("Net Worth (M)", ascending = False).head(3)

,Name,Age,Gender,Retired?,Net Worth (M),Grand Slam Titles,Country,Playing Style
1,Roger Federer,45,M,Yes,420.0,20,Switzerland,All-round
5,Rafael Nadal,40,M,Yes,220.0,22,Spain,Left-handed
2,Novak Djokovic,39,M,No,180.0,24,Serbia,All-round

In [42]:
df.sort_values("Grand Slam Titles", ascending = False).head(3)

,Name,Age,Gender,Retired?,Net Worth (M),Grand Slam Titles,Country,Playing Style
2,Novak Djokovic,39,M,No,180.0,24,Serbia,All-round
5,Rafael Nadal,40,M,Yes,220.0,22,Spain,Left-handed
1,Roger Federer,45,M,Yes,420.0,20,Switzerland,All-round

In [46]:
df[(df["Grand Slam Titles"] >= 2) & (df["Age"] <= 30)]

,Name,Age,Gender,Retired?,Net Worth (M),Grand Slam Titles,Country,Playing Style
3,Carlos Alcaraz,23,M,No,85.0,2,Spain,Aggressive
4,Aryna Sabalenka,28,F,No,27.4,4,Belarus,Aggressive
6,Iga Swiatek,25,M,No,30.0,6,Poland,Baseline
7,Jannik Sinner,25,M,No,20.0,4,Italy,Baseline

In [47]:
df["Country"].value_counts()

Country
Spain          2
Switzerland    1
Serbia         1
Belarus        1
Poland         1
Italy          1
USA            1
Name: count, dtype: int64

In [48]:
df["Playing Style"].value_counts()

Playing Style
Aggressive     3
All-round      2
Baseline       2
Left-handed    1
Name: count, dtype: int64

In [51]:
df.groupby("Gender")["Net Worth (M)"].sum()

Gender
F     42.4
M    955.0
Name: Net Worth (M), dtype: float64

In [52]:
df.groupby("Gender")["Net Worth (M)"].mean()

Gender
F     21.200000
M    159.166667
Name: Net Worth (M), dtype: float64

In [53]:
df.groupby("Playing Style")["Grand Slam Titles"].mean()

Playing Style
Aggressive      2.333333
All-round      22.000000
Baseline        5.000000
Left-handed    22.000000
Name: Grand Slam Titles, dtype: float64

In [54]:
df.groupby("Gender")["Grand Slam Titles"].sum()

Gender
F     5
M    78
Name: Grand Slam Titles, dtype: int64